### ISSUE TITLE
Formatowanie tekstu w prezentacji

### ISSUE THREAD

**Issue by ksawery-brzeski** [daftcode/daftacademy-frontend4beginners-autumn2019#1]
W prezentacji 1., w sekcji "grafika" tytuł się źle wyświetla

**Comment by mdycz** [comment]
Hej, wydaje mi się że wszystko wygląda poprawnie, czy jesteś w stanie wrzucić screenshota?

**Comment by ksawery-brzeski** [comment]
![2019-11-18](https://user-images.githubusercontent.com/55759470/69138260-a0704e00-0abe-11ea-94f0-5f274716719b.png)

**Comment by ksawery-brzeski** [comment]
Dokładniej problem jest taki, że w edge'u (w firefoksie, chromie i chromium nie ma tego problemu) nie wyświetlają się litery 'f'

**Comment by scieplak** [comment]
Cześć!
Problem spowodowany jest tym, że Github renderuje pliki pdf jako html w przeglądarce ([link](https://github.blog/2015-03-17-pdf-viewing/)), a rzadziej wykorzystywane przeglądarki mogą wyświetlać inaczej niektóre elementy (wspominał o tym Mikołaj na zajęciach). Wrzuciliśmy plik pdf z myślą, że zostanie on przez Was pobrany i otwarty w przeznaczonym do tego środowisku. 

Polecamy to zrobić w tym wypadku, bo jak widać - edge nie do końca ogarnia githubowe wyświetlanie pdfów  :)
