### ISSUE TITLE
border-top na różnych rozdzielczościach

### ISSUE THREAD

**Issue by Kunek** [daftcode/daftacademy-frontend4beginners-autumn2019#10]
Niepoprawnie działa mi border-top zarówno na rozdzielczości 1366 x 768 jak i 1920x1080, nie potrafię znaleźć przyczyny tego zachowania. Chcę zrobić stronę pod rozdzielczość 1366 x 768.

![border](https://user-images.githubusercontent.com/52375941/69569882-e5184f80-0fbe-11ea-8a50-7888d1624b5b.PNG)
![border2](https://user-images.githubusercontent.com/52375941/69569883-e5184f80-0fbe-11ea-8569-63b68b8cc358.PNG)

**Comment by izeRR** [comment]
Pokaż fragment kodu odpowiedzialnego u Ciebie za to ;)
Najprawdopodobniej nie do tego elementu przyczepiasz border-top.

**Comment by Kunek** [comment]
![html_border](https://user-images.githubusercontent.com/52375941/69571525-8654d500-0fc2-11ea-9553-c63497929d81.PNG)
![css_border](https://user-images.githubusercontent.com/52375941/69571533-881e9880-0fc2-11ea-9060-4cfd2836a25b.PNG)

**Comment by izeRR** [comment]
Robisz cokolwiek z img? To on Ci rozwala efekt, ponieważ na różnych rozdzielczościach inaczej ma miejsce, dlatego w pewnym momencie wyskakuje z klasy border-top. 
Jedno z rozwiązań? Przenieś regułę z .border-top, na img, czy to poprzez klasę czy selektor klasy i elementu. Ewentualnie zadbaj o to, by img nie wyskakiwał Ci z .border-top

**Comment by Kunek** [comment]
Dzięki, działa na obu ekranach.
