### ISSUE TITLE
<alt> dla zdjęć artystycznych

### ISSUE THREAD

**Issue by ghost** [daftcode/daftacademy-frontend4beginners-autumn2019#11]
Cześć! 
Czy warto opisywać zdjęcia przy pomocy <alt> na stronach z portfolio fotografów? I jeśli tak, to jak wyznaczyć, ile i co pisać, czy to musi być precyzyjny opis wszystkiego, co się znajduje na zdjęciu? Chodzi mi np o takie strony: http://rafalmilach.com/

**Comment by vshishko** [comment]
Raczej zalecane jest aby tagi ALT były zwięzłe. Gdy opis obrazu wymaga więcej szczegółów, to zaleca się, aby w ALT odsyłał do opisu tekstowego w innym miejscu.
Tu jest spoko opisane: https://accessibility.psu.edu/images/alttext/

**Comment by nezouse** [comment]
Dobrym przykładem altów do takich zdjęć będą te z instagrama.  Alt powinien być napisany zawsze, gdy zdjęcie jest treścią strony, a nie tylko jej dekoracją. 
(Wszystkie alty na instagramie wyglądają prawie tak samo bo są generowane automatycznie.)
