### ISSUE TITLE
2 formularze do zgłaszania pracy domowej nr 4

### ISSUE THREAD

**Issue by pnalewczynski** [daftcode/daftacademy-frontend4beginners-autumn2019#26]
Zauważyłem pewną nieścisłość. Z tego co widzę udostępniliście dwa różne linki, do dwóch różnych formularzy (praca domowa nr 4):

https://docs.google.com/forms/d/e/1FAIpQLSez5MNNrRoz8C5xldLJ-SImqTz0ZyBA-EXR4dnQp6B8x9t05g/viewform - ten link znajdował się w wiadomości e-mail,

https://docs.google.com/forms/d/e/1FAIpQLSfwFut13Q3iabDUfzq-7Rxrtq1BXIrCC3f1A0AYSqMPPYrdjg/viewform - ten link znajdował się w [Issues Github](https://github.com/daftcode/daftacademy-frontend4beginners-autumn2019/issues/24#issuecomment-565981494).

Zdziwiło mnie, że nie ma możliwości otrzymania kopii na swój e-mail, ale wysyłałem wczoraj zgłoszenie używając tego pierwszego. 

Nie ma to znaczenia i wszystko ok?

**Comment by scieplak** [comment]
Posiadamy odpowiedzi z obydwu formularzy, więc wszystko powinno być w porządku.
Dodatkowo spojrzałem teraz na listę odpowiedzi i jest Twoje zgłoszenie, możesz być spokojny :)

**Comment by pnalewczynski** [comment]
Dzięki za odpowiedź! :)
